name: Test Homebrew Formula
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [macos-13, macos-14] # macos-13 is Intel, macos-14 is Apple Silicon
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install and test formula
        run: |
          brew install .
          brew test .